name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright_tests_job:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  artillery_load_test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright and Artillery
        run: |
          npx playwright install --with-deps
          npm install -g artillery@latest

      - name: Execute load tests
        run: artillery run load-tests/artillery.yml --record
        env:
          ARTILLERY_CLOUD_API_KEY: ${{ secrets.ARTILLERY_API_KEY }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: artillery-report
          path: Artillery/test-run-report.json
